// Core dependencie
import { ENS_DEFINITIONS, ENS_USE_CASE_CONFIGS } from './ens'
import { UTILITY_DEFINITIONS, UTILITY_USE_CASE_CONFIGS } from './utility'
import { ERC20_DEFINITIONS } from './token/erc20'
import { ERC721_DEFINITIONS } from './token/erc721'
import {
    ERC3643_DEFINITIONS,
    ERC203643_SHARED_DEFINITIONS,
} from './token/erc3643'
// Import token use case configurations
import { ERC20_USE_CASE_CONFIGS } from './erc20'
import { ERC721_USE_CASE_CONFIGS } from './token/erc721_configurations'
import { ERC3643_USE_CASE_CONFIGS } from './token/erc3643_configurations'

// Export core constants
export { DEFAULT_VERSION } from './version'
export { CONFIGURATION_IDS } from './configurationIds'

// Export resolver keys
export * from './resolverKeys'

// Export token configurations
export * from './erc20'
export * from './erc721'
export * from './token/erc3643'

// Export feature definitions
export * from './ens'
export * from './utility'

// Export utility functions
export { buildConfigurationId } from '../utils/configurationUtils'

// Default governance configuration
export const DEFAULT_GOVERNANCE_CONFIG = {
    isOwnable: true,
    rbacs: [],
    initPause: false,
    initBusinessIds: [],
    initCallData: [],
    initData: '0x',
}

// Default use case configurations
export const DEFAULT_USE_CASE_CONFIGURATIONS = [
    // ENS use cases
    ENS_USE_CASE_CONFIGS.PUBLIC_RESOLVER,

    // Utility use cases
    UTILITY_USE_CASE_CONFIGS.HASH_TIMESTAMP,

    // ERC20 use cases - Base and Single Extensions
    ERC20_USE_CASE_CONFIGS.BASE,
    ERC20_USE_CASE_CONFIGS.WITH_BURNABLE,
    ERC20_USE_CASE_CONFIGS.WITH_CAPPED,
    ERC20_USE_CASE_CONFIGS.WITH_CONTROLLER,
    ERC20_USE_CASE_CONFIGS.WITH_SNAPSHOT,

    // ERC20 use cases - Two Extension Combinations
    ERC20_USE_CASE_CONFIGS.BURNABLE_SNAPSHOT,
    ERC20_USE_CASE_CONFIGS.BURNABLE_CAPPED,
    ERC20_USE_CASE_CONFIGS.BURNABLE_CONTROLLER,
    ERC20_USE_CASE_CONFIGS.SNAPSHOT_CAPPED,
    ERC20_USE_CASE_CONFIGS.SNAPSHOT_CONTROLLER,
    ERC20_USE_CASE_CONFIGS.CAPPED_CONTROLLER,

    // ERC20 use cases - Three extension combinations
    ERC20_USE_CASE_CONFIGS.BURNABLE_SNAPSHOT_CAPPED,
    ERC20_USE_CASE_CONFIGS.BURNABLE_SNAPSHOT_CONTROLLER,
    ERC20_USE_CASE_CONFIGS.BURNABLE_CAPPED_CONTROLLER,
    ERC20_USE_CASE_CONFIGS.SNAPSHOT_CAPPED_CONTROLLER,

    // Complete configuration (all 4 extensions)
    ERC20_USE_CASE_CONFIGS.COMPLETE,

    // ERC3643 Security Token
    ERC3643_USE_CASE_CONFIGS.SECURITY_TOKEN,

    // ERC721 use cases - Base and Single Extensions
    ERC721_USE_CASE_CONFIGS.BASE,
    ERC721_USE_CASE_CONFIGS.WITH_BURNABLE,
    ERC721_USE_CASE_CONFIGS.WITH_ENUMERABLE,
    ERC721_USE_CASE_CONFIGS.WITH_CAPPED,
    ERC721_USE_CASE_CONFIGS.WITH_CONTROLLER,
    ERC721_USE_CASE_CONFIGS.WITH_SNAPSHOT,
    ERC721_USE_CASE_CONFIGS.WITH_ROYALTY,
    ERC721_USE_CASE_CONFIGS.WITH_CONSECUTIVE,

    // ERC721 use cases - Two extension combinations
    // Burnable combinations
    ERC721_USE_CASE_CONFIGS.BURN_ENUM,
    ERC721_USE_CASE_CONFIGS.BURN_CAP,
    ERC721_USE_CASE_CONFIGS.BURN_CTRL,
    ERC721_USE_CASE_CONFIGS.BURN_SNAP,
    ERC721_USE_CASE_CONFIGS.BURN_ROY,
    ERC721_USE_CASE_CONFIGS.BURN_CONS,

    // Enumerable combinations
    ERC721_USE_CASE_CONFIGS.ENUM_CAP,
    ERC721_USE_CASE_CONFIGS.ENUM_CTRL,
    ERC721_USE_CASE_CONFIGS.ENUM_SNAP,
    ERC721_USE_CASE_CONFIGS.ENUM_ROY,
    ERC721_USE_CASE_CONFIGS.ENUM_CONS,

    // Capped combinations
    ERC721_USE_CASE_CONFIGS.CAP_CTRL,
    ERC721_USE_CASE_CONFIGS.CAP_SNAP,
    ERC721_USE_CASE_CONFIGS.CAP_ROY,
    ERC721_USE_CASE_CONFIGS.CAP_CONS,

    // Controller combinations
    ERC721_USE_CASE_CONFIGS.CTRL_SNAP,
    ERC721_USE_CASE_CONFIGS.CTRL_ROY,
    ERC721_USE_CASE_CONFIGS.CTRL_CONS,

    // Snapshot combinations
    ERC721_USE_CASE_CONFIGS.SNAP_ROY,
    ERC721_USE_CASE_CONFIGS.SNAP_CONS,

    // Royalty combinations
    ERC721_USE_CASE_CONFIGS.ROY_CONS,

    // ERC721 use cases - Three extension combinations
    // Burnable + Enumerable combinations
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_CAP,
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_CTRL,
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_SNAP,
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_ROY,
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_CONS,

    ERC721_USE_CASE_CONFIGS.BURN_SNAP_ROY,
    ERC721_USE_CASE_CONFIGS.BURN_SNAP_CONS,
    ERC721_USE_CASE_CONFIGS.BURN_ROY_CONS,

    // Enumerable combinations
    ERC721_USE_CASE_CONFIGS.ENUM_CAP_CTRL,
    ERC721_USE_CASE_CONFIGS.ENUM_CAP_SNAP,
    ERC721_USE_CASE_CONFIGS.ENUM_CAP_ROY,
    ERC721_USE_CASE_CONFIGS.ENUM_CAP_CONS,
    ERC721_USE_CASE_CONFIGS.ENUM_CTRL_SNAP,
    ERC721_USE_CASE_CONFIGS.ENUM_CTRL_ROY,
    ERC721_USE_CASE_CONFIGS.ENUM_CTRL_CONS,
    ERC721_USE_CASE_CONFIGS.ENUM_SNAP_ROY,
    ERC721_USE_CASE_CONFIGS.ENUM_SNAP_CONS,
    ERC721_USE_CASE_CONFIGS.ENUM_ROY_CONS,

    // Capped combinations
    ERC721_USE_CASE_CONFIGS.CAP_CTRL_SNAP,
    ERC721_USE_CASE_CONFIGS.CAP_CTRL_ROY,
    ERC721_USE_CASE_CONFIGS.CAP_CTRL_CONS,
    ERC721_USE_CASE_CONFIGS.CAP_SNAP_ROY,
    ERC721_USE_CASE_CONFIGS.CAP_SNAP_CONS,
    ERC721_USE_CASE_CONFIGS.CAP_ROY_CONS,

    // Controller combinations
    ERC721_USE_CASE_CONFIGS.CTRL_SNAP_ROY,
    ERC721_USE_CASE_CONFIGS.CTRL_SNAP_CONS,
    ERC721_USE_CASE_CONFIGS.CTRL_ROY_CONS,

    // Snapshot combinations
    ERC721_USE_CASE_CONFIGS.SNAP_ROY_CONS,

    // ERC721 use cases - Four extension combinations
    // BURN + ENUM combinations
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_CAP_CTRL,
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_CAP_SNAP,
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_CAP_ROY,
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_CAP_CONS,
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_CTRL_SNAP,
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_CTRL_ROY,
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_CTRL_CONS,
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_SNAP_ROY,
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_SNAP_CONS,
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_ROY_CONS,

    // BURN + CAP combinations
    ERC721_USE_CASE_CONFIGS.BURN_CAP_CTRL_SNAP,
    ERC721_USE_CASE_CONFIGS.BURN_CAP_CTRL_ROY,
    ERC721_USE_CASE_CONFIGS.BURN_CAP_CTRL_CONS,
    ERC721_USE_CASE_CONFIGS.BURN_CAP_SNAP_ROY,
    ERC721_USE_CASE_CONFIGS.BURN_CAP_SNAP_CONS,
    ERC721_USE_CASE_CONFIGS.BURN_CAP_ROY_CONS,

    // BURN + CTRL combinations
    ERC721_USE_CASE_CONFIGS.BURN_CTRL_SNAP_ROY,
    ERC721_USE_CASE_CONFIGS.BURN_CTRL_SNAP_CONS,
    ERC721_USE_CASE_CONFIGS.BURN_CTRL_ROY_CONS,

    // BURN + SNAP combinations
    ERC721_USE_CASE_CONFIGS.BURN_SNAP_ROY_CONS,

    // ENUM + CAP combinations
    ERC721_USE_CASE_CONFIGS.ENUM_CAP_CTRL_SNAP,
    ERC721_USE_CASE_CONFIGS.ENUM_CAP_CTRL_ROY,
    ERC721_USE_CASE_CONFIGS.ENUM_CAP_CTRL_CONS,
    ERC721_USE_CASE_CONFIGS.ENUM_CAP_SNAP_ROY,
    ERC721_USE_CASE_CONFIGS.ENUM_CAP_SNAP_CONS,
    ERC721_USE_CASE_CONFIGS.ENUM_CAP_ROY_CONS,

    // ENUM + CTRL combinations
    ERC721_USE_CASE_CONFIGS.ENUM_CTRL_SNAP_ROY,
    ERC721_USE_CASE_CONFIGS.ENUM_CTRL_SNAP_CONS,
    ERC721_USE_CASE_CONFIGS.ENUM_CTRL_ROY_CONS,

    // ENUM + SNAP combinations
    ERC721_USE_CASE_CONFIGS.ENUM_SNAP_ROY_CONS,

    // CAP + CTRL combinations
    ERC721_USE_CASE_CONFIGS.CAP_CTRL_SNAP_ROY,
    ERC721_USE_CASE_CONFIGS.CAP_CTRL_SNAP_CONS,
    ERC721_USE_CASE_CONFIGS.CAP_CTRL_ROY_CONS,

    // CAP + SNAP combinations
    ERC721_USE_CASE_CONFIGS.CAP_SNAP_ROY_CONS,

    // CTRL + SNAP combinations
    ERC721_USE_CASE_CONFIGS.CTRL_SNAP_ROY_CONS,

    // ERC721 use cases - Five extension combinations
    // BURN + ENUM combinations
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_CAP_CTRL_SNAP,
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_CAP_CTRL_ROY,
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_CAP_CTRL_CONS,
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_CAP_SNAP_ROY,
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_CAP_SNAP_CONS,
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_CAP_ROY_CONS,
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_CTRL_SNAP_ROY,
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_CTRL_SNAP_CONS,
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_CTRL_ROY_CONS,

    // BURN + CAP combinations
    ERC721_USE_CASE_CONFIGS.BURN_CAP_CTRL_SNAP_ROY,
    ERC721_USE_CASE_CONFIGS.BURN_CAP_CTRL_SNAP_CONS,
    ERC721_USE_CASE_CONFIGS.BURN_CAP_CTRL_ROY_CONS,

    // ENUM + CAP combinations
    ERC721_USE_CASE_CONFIGS.ENUM_CAP_CTRL_SNAP_ROY,
    ERC721_USE_CASE_CONFIGS.ENUM_CAP_CTRL_SNAP_CONS,
    ERC721_USE_CASE_CONFIGS.ENUM_CAP_CTRL_ROY_CONS,

    // CAP + CTRL combinations
    ERC721_USE_CASE_CONFIGS.CAP_CTRL_SNAP_ROY_CONS,
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_CAP_CTRL_SNAP,
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_CAP_CTRL_ROY,
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_CAP_CTRL_CONS,
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_CAP_SNAP_ROY,
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_CAP_SNAP_CONS,
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_CAP_ROY_CONS,
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_CTRL_SNAP_ROY,
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_CTRL_SNAP_CONS,
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_CTRL_ROY_CONS,
    ERC721_USE_CASE_CONFIGS.BURN_CAP_CTRL_SNAP_ROY,
    ERC721_USE_CASE_CONFIGS.BURN_CAP_CTRL_SNAP_CONS,
    ERC721_USE_CASE_CONFIGS.BURN_CAP_CTRL_ROY_CONS,
    ERC721_USE_CASE_CONFIGS.ENUM_CAP_CTRL_SNAP_ROY,
    ERC721_USE_CASE_CONFIGS.ENUM_CAP_CTRL_SNAP_CONS,
    ERC721_USE_CASE_CONFIGS.ENUM_CAP_CTRL_ROY_CONS,
    ERC721_USE_CASE_CONFIGS.CAP_CTRL_SNAP_ROY_CONS,

    // ERC721 use cases - Six extension combinations
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_CAP_CTRL_SNAP_ROY,
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_CAP_CTRL_SNAP_CONS,
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_CAP_CTRL_ROY_CONS,
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_CAP_SNAP_ROY_CONS,
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_CTRL_SNAP_ROY_CONS,
    ERC721_USE_CASE_CONFIGS.BURN_CAP_CTRL_SNAP_ROY_CONS,
    ERC721_USE_CASE_CONFIGS.ENUM_CAP_CTRL_SNAP_ROY_CONS,

    // ERC721 use cases - Seven extension combinations
    ERC721_USE_CASE_CONFIGS.BURN_ENUM_CAP_CTRL_SNAP_ROY_CONS,
    /* Total use cases currently deployed:
      DID: 1 Base Registry
      ENS: 2 (Registry & Public Resolver)
      Utility: 1 (Hash Timestamp Service)
      Client: 1 (Client Filtering)
      TSA: 1 (TimeStamping Authority)
      TSR: 1 (TimeStamping Registry)
      ERC20: 16 variations
      ERC721: Total 60 variations:
        + 1 Base
        + 7 Single Extensions C(7,1)
        + 21 Double Extensions C(7,2)
        + 25 Triple Extensions C(7,3) [subset]
        + 4 Four Extensions [subset]
        + 16 Five Extensions
        + 6 Six Extensions
        + 0 Complete (All 7 Extensions)
      Total Deployed Use Cases = 83 */
]

// Combine all business logic definitions
export const BUSINESS_LOGIC_DEFINITIONS = [
    ...UTILITY_DEFINITIONS,
    ...ENS_DEFINITIONS,
    ...ERC20_DEFINITIONS,
    ...ERC203643_SHARED_DEFINITIONS, // Shared facets between ERC20 and ERC3643
    ...ERC721_DEFINITIONS,
    ...ERC3643_DEFINITIONS,
]
