/* -----------------------------------------------------------------------------------
Copyright (c) 2025 Comunidad de Madrid & Alastria
Licensed under the Apache License, Version 2.0 (the "License");
You may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
----------------------------------------------------------------------------------- */
BigInt.prototype.toJSON = function () {
    return this.toString()
}
import { HardhatUserConfig } from 'hardhat/config'
import '@nomicfoundation/hardhat-toolbox'
import '@nomicfoundation/hardhat-chai-matchers'
import '@typechain/hardhat'
import 'hardhat-contract-sizer'
import 'solidity-docgen'
import 'hardhat-gas-reporter'

// Configure dotenv globally without verbose logging
import 'dotenv/config'

// Import unified configuration and task utilities
import { getNetworkConfigs, ConfigManager, logger } from './config'

// Register all tasks with Hardhat CLI in a single import
// This replaces the many individual task imports with a consolidated approach
import './tasks/register'
import { EthGasReporterConfig } from 'hardhat-gas-reporter/dist/src/types'

// Initialize configuration management
const configManager = ConfigManager.getInstance()

// Validate configuration and log results
const configValidation = configManager.validateConfiguration()
if (!configValidation.isValid) {
    logger.error('❌ Configuration validation failed:')
    configValidation.errors.forEach((error) => logger.error(`  - ${error}`))
    logger.warn('⚠️  Continuing with potentially invalid configuration')
}

if (configValidation.warnings.length > 0) {
    logger.warn('⚠️  Configuration warnings:')
    configValidation.warnings.forEach((warning) =>
        logger.warn(`  - ${warning}`)
    )
}

// Log configuration summary (respects debug mode)
const summary = configValidation.summary
logger.summary('Configuration Summary', {
    environment: summary.environment,
    networksCount: summary.networksCount,
    secp256k1Networks: summary.secp256k1Networks,
    secp256r1Networks: summary.secp256r1Networks,
    accountsCount: summary.accountsCount,
    gasLimit: summary.gasLimit,
    timeout: `${summary.timeout}ms`,
})

// Get network configurations from unified config
const networkConfigs = getNetworkConfigs()

// const ACCOUNTS = (
//     process.env.ACCOUNTS ?? randomBytes(32).toString('hex')
// ).split(',')
const config: HardhatUserConfig = {
    solidity: {
        version: '0.8.28',
        settings: {
            evmVersion: 'istanbul',
            optimizer: {
                enabled: true,
                runs: 1000,
            },
        },
    },
    networks: networkConfigs,
    mocha: {
        timeout: configManager.getTestingConfig().timeout,
        parallel: configManager.getTestingConfig().parallel,
    },
    paths: {
        sources: './contracts',
        tests: './test',
        cache: './cache',
        artifacts: './artifacts',
    },
    contractSizer: {
        alphaSort: true,
        disambiguatePaths: false,
        runOnCompile: true,
        strict: true,
    },
    docgen: {
        outputDir: 'docs/generated-temp',
        pages: 'items',
        exclude: ['testwrapper'],
        collapseNewlines: true,
    },
    gasReporter: {
        enabled: process.env.REPORT_GAS === 'true',
        showMethodSig: true,
        includeIntrinsicGas: false,
        reportPureAndViewMethods: true,
        excludeAutoGeneratedGetters: true,
        reportFormat: 'markdown',
        outputFile: 'docs/generated/gas-usage-summary.md',
        noColors: true,
        currency: 'EUR',
    } as Partial<EthGasReporterConfig>,
}

export default config
