@startuml
title Arquitectura de SC ISBE

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}
skinparam linetype polyline
hide empty members

' === CORE ===
package "Core" {
    class Common <<(A,#228b22) abstract contract>>
    Common--|> ERC165Internal
    Common--|> AccessControlInternal 
    Common--|> OwnableInternal
    Common--|> BasicWhitelistInternal
    Common--|> PauseInternalCommon
    

     ' --- Context---
    class ISBEContext <<(A,#228b22) abstract contract>> #4682B4
    class Context <<(A,#228b22) abstract contract>> #4682B4
    ISBEContext --|> Context
 

    ' --- AccessControl---
    class IAccessControlEoa<<(I,#FFD700) interface>> #77DD77
    class IAccessControlDid<<(I,#FFD700) interface>> #77DD77
    class AccessControlInternal <<(A,#228B22) abstract contract>> #77DD77
    class AccessControl <<(A,#228B22) abstract contract>> #77DD77
    class AccessControlDid<<(A,#228B22) abstract contract>> #77DD77
    class AccessControlFacet<<(C,#1E90FF) contract>> #77DD77
    class AccessControlDidFacet<<(C,#1E90FF) contract>> #77DD77

    AccessControlFacet--|> AccessControl 
    AccessControl --|> IAccessControlEoa
    AccessControl --|> Common
    AccessControlDidFacet--|> AccessControlDid
    AccessControlDid--|> IAccessControlDid
    AccessControlDid--|> Common
    
    AccessControlInternal --|> ISBEContext
    AccessControlInternal --|> IsbeFactoryInternal

    ' --- Ownable---
    class IOwnable<<(I,#FFD700) interface>> #E6E6FA
    class IOwnable2Step<<(I,#FFD700) interface>> #E6E6FA
    class Ownable2StepInternal <<(A,#228B22) abstract contract>> #E6E6FA
    class OwnableInternal<<(A,#228B22) abstract contract>> #E6E6FA

    class OwnableBase<<(A,#228B22) abstract contract>> #E6E6FA
    class Ownable<<(A,#228B22) abstract contract>> #E6E6FA
    class Ownable2Step<<(A,#228B22) abstract contract>> #E6E6FA

    class OwnableFacet<<(C,#1E90FF) contract>> #E6E6FA
    class Ownable2StepFacet<<(C,#1E90FF) contract>> #E6E6FA


    Ownable--|> OwnableBase
    Ownable2Step--|> IOwnable2Step
    Ownable2Step--|> OwnableBase
    Ownable2Step--|> Ownable2StepInternal
    Ownable2StepFacet--|> Ownable2Step
    Ownable2StepInternal--|> OwnableInternal
    OwnableBase--|> IOwnable
    OwnableBase--|> Common
    OwnableFacet--|> Ownable
    OwnableInternal--|> ISBEContext
    

   ' --- BasicWhitelist---
    class IBasicWhitelist<<(I,#FFD700) interface>> #FFFF99
    class BasicWhitelistInternal<<(A,#228B22) abstract contract>> #FFFF99
    class BasicWhitelist<<(A,#228B22) abstract contract>> #FFFF99
    class BasicWhitelistFacet<<(C,#1E90FF) contract>> #FFFF99

    BasicWhitelistFacet--|> BasicWhitelist
    BasicWhitelist--|> IBasicWhitelist
    BasicWhitelist--|> Common


    ' --- Pause---
    class IPause<<(I,#FFD700) interface>> #FFB6C1
    class ISBEPause<<(A,#228B22) abstract contract>> #FFB6C1
    class Pause<<(A,#228B22) abstract contract>> #FFB6C1
    class PauseInternal<<(A,#228B22) abstract contract>> #FFB6C1
    class PauseInternalCommon<<(A,#228B22) abstract contract>> #FFB6C1
    class ISBEPauseFacet<<(C,#1E90FF) contract>> #FFB6C1
    
    ISBEPause--|> Pause
    ISBEPauseFacet--|> ISBEPause
    Pause--|> IPause
    Pause--|> PauseInternal
    PauseInternal--|> Common
    PauseInternalCommon--|> ISBEContext
    

   ' --- 165---
    class IERC165<<(I,#FFD700) interface>> #6A5ACD
    class ERC165Internal<<(A,#228B22) abstract contract>> #6A5ACD
    class ERC165<<(A,#228B22) abstract contract>> #6A5ACD

    ERC165--|> IERC165
    ERC165--|> ERC165Internal
    

    ' --- Initializable---
    class Initializable<<(A,#228B22) abstract contract>> #D2B48C

    Common --|> Initializable


}
@enduml