@startuml
title Arquitectura de SC ISBE

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}
skinparam linetype polyline
hide empty members

' === CORE ===
package "Core" {
    class Initializable <<(A,#228b22) abstract contract>>
    class Common <<(A,#228b22) abstract contract>>
    class LibCommon << (L,#FF7700) library >>
    class ISBEContext <<(A,#228b22) abstract contract>>
    class AccessControlInternal <<(A,#228b22) abstract contract>> 
    class PauseInternalCommon <<(A,#228b22) abstract contract>> 
    class OwnableInternal <<(A,#228b22) abstract contract>> 
    class ERC165Internal <<(A,#228b22) abstract contract>>
    class Context <<(A,#228b22) abstract contract>>

    Common --|> Initializable
    Common --|> ERC165Internal
    Common --|> AccessControlInternal
    Common --|> OwnableInternal
    Common --|> PauseInternalCommon
    PauseInternalCommon --|> ISBEContext
    OwnableInternal --|> ISBEContext
    ISBEContext --|> Context
    AccessControlInternal --|> LibCommon
}




' === ERC20 and ERC3643 ===
package "ERC20 and ERC3643" {
    class IERC20 <<(I,#FFD700) interface>> #FFB6C1
    class IERC20Metadata <<(I,#FFD700) interface>> #FFB6C1
    class IERC20Isbe <<(I,#FFD700) interface>> #FFB6C1
    class IERC20Burnable <<(I,#FFD700) interface>> #FFB6C1
    class IERC20Snapshot <<(I,#FFD700) interface>> #FFB6C1
    class IERC203643Capped <<(I,#FFD700) interface>> #FFFF99
    class IERC203643Controller <<(I,#FFD700) interface>> #FFFF99
    

    class ERC20 <<(A,#228B22) abstract contract>> #FFB6C1
    class ERC20Facet <<(C,#1E90FF) contract>> #FFB6C1
    class ERC20Internal <<(A,#228B22) abstract contract>> #FFB6C1

    class ERC20Burnable <<(A,#228B22) abstract contract>> #FFB6C1
    class ERC20BurnableFacet <<(C,#1E90FF) contract>> #FFB6C1

    class ERC20Snapshot <<(A,#228B22) abstract contract>> #FFB6C1
    class ERC20SnapshotFacet <<(C,#1E90FF) contract>> #FFB6C1
    class ERC20SnapshotInternal <<(A,#228B22) abstract contract>> #FFB6C1

    class ERC203643Capped <<(A,#228B22) abstract contract>> #FFFF99
    class ERC203643CappedFacet <<(C,#1E90FF) contract>> #FFFF99
    class ERC203643CappedInternal <<(A,#228B22) abstract contract>> #FFFF99

    class ERC203643Controller <<(A,#228B22) abstract contract>> #FFFF99
    class ERC203643ControllerFacet <<(C,#1E90FF) contract>> #FFFF99

    

    ERC20 --|> IERC20Isbe
    IERC20Isbe --|> IERC20
    IERC20Isbe --|> IERC20Metadata
    
  
    ERC20Internal --|> Common
    ERC20Facet --|> ERC20

    ERC20Burnable --|> IERC20Burnable
    ERC20BurnableFacet --|> ERC20Burnable

    ERC203643Capped --|> IERC203643Capped
    ERC203643CappedFacet --|> ERC203643Capped
    ERC203643CappedInternal --|> ERC20Internal

    ERC203643Controller --|> IERC203643Controller
    ERC203643ControllerFacet --|> ERC203643Controller

    ERC20Snapshot --|> IERC20Snapshot
    ERC20SnapshotFacet --|> ERC20Snapshot
    ERC20SnapshotInternal --|> ERC20Internal



    ' --- Metadata ---
    class IERC3643Metadata <<(I,#FFD700) interface>> #E6E6FA
    class ERC3643MetadataInternal <<(A,#228B22) abstract contract>> #E6E6FA
    class ERC3643Metadata <<(A,#228B22) abstract contract>> #E6E6FA
    class ERC3643MetadataFacet <<(C,#1E90FF) contract>> #E6E6FA

    ERC3643MetadataFacet --|> ERC3643Metadata 
    ERC3643Metadata --|> IERC3643Metadata   
    ERC3643MetadataInternal --|> Common 


    ' --- Freeze ---
    class IERC3643Freeze <<(I,#FFD700) interface>> #E6E6FA
    class ERC3643FreezeInternal <<(A,#228B22) abstract contract>> #E6E6FA
    class ERC3643Freeze <<(A,#228B22) abstract contract>> #E6E6FA
    class ERC3643FreezeFacet <<(C,#1E90FF) contract>> #E6E6FA

    ERC3643FreezeFacet --|> ERC3643Freeze
    ERC3643Freeze --|> IERC3643Freeze  
    ERC3643FreezeInternal --|> Common 

    ' --- Compliance---
    class ICompliance <<(I,#FFD700) interface>> #77DD77
    class ERC3643ComplianceInternal <<(A,#228B22) abstract contract>> #77DD77
    class ERC3643Compliance <<(A,#228B22) abstract contract>> #77DD77
    class ERC3643ComplianceFacet <<(C,#1E90FF) contract>> #77DD77
    
    ERC3643ComplianceFacet --|> ERC3643Compliance
    ERC3643Compliance --|> ICompliance   
    ERC3643ComplianceInternal --|> Common

    ' --- Compliance Max Balance---
    class IERC3643ComplianceMaxBalance <<(I,#FFD700) interface>> #77DD77
    class ERC3643ComplianceMaxBalanceInternal <<(A,#228B22) abstract contract>> #77DD77
    class ERC3643ComplianceMaxBalance <<(A,#228B22) abstract contract>> #77DD77
    class ERC3643ComplianceMaxBalanceFacet <<(C,#1E90FF) contract>> #77DD77
    
    ERC3643ComplianceMaxBalanceFacet --|> ERC3643ComplianceMaxBalance
    ERC3643ComplianceMaxBalance --|> IERC3643ComplianceMaxBalance 
    ERC3643ComplianceMaxBalanceInternal --|> Common

    ERC3643ComplianceInternal --|> ERC3643ComplianceMaxBalanceInternal 
    

    ' --- ERC203643 Internal Common ---
    class ERC203643InternalCommon <<(A,#228B22) abstract contract>> #FFFF99
    ERC203643InternalCommon --|> ERC20SnapshotInternal
    ERC203643InternalCommon --|> ERC203643CappedInternal
    ERC203643InternalCommon --|> ERC3643FreezeInternal
    ERC203643InternalCommon --|> ERC3643MetadataInternal 
    ERC203643InternalCommon --|> ERC3643ComplianceInternal


    ERC3643Metadata --|> ERC203643InternalCommon
    ERC3643Freeze --|> ERC203643InternalCommon
    ERC20 --|> ERC203643InternalCommon
    ERC20Burnable --|> ERC203643InternalCommon
    ERC203643Capped --|> ERC203643InternalCommon
    ERC203643Controller --|> ERC203643InternalCommon
    ERC20Snapshot --|> ERC203643InternalCommon
    ERC3643Compliance --|> ERC203643InternalCommon
    ERC3643ComplianceMaxBalance --|> ERC203643InternalCommon

    


}
@enduml