@startuml
title Arquitectura de SC ISBE

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}
skinparam linetype polyline
hide empty members

' === CORE ===
package "Core" {

  ' --- DID and VRelationShip---
    class DidDocumentDetailedInternal <<(A,#228b22) abstract contract>> #9370DB
    class VRelationshipsInternal <<(A,#228b22) abstract contract>> #9370DB

    DidDocumentDetailedInternal --|> Common
    DidDocumentDetailedInternal --|> VRelationshipsInternal 
    VRelationshipsInternal--|> ISBEContext
}




' === ERC20 and ERC3643 ===
package "ERC20 and ERC3643" {

        ' --- ERC203643 Internal Common ---
    class ERC203643InternalCommon <<(A,#228B22) abstract contract>> #FFFF99
    
    ' --- ERC20---
    class IERC20 <<(I,#FFD700) interface>> #FFB6C1
    class IERC20Isbe <<(I,#FFD700) interface>> #FFB6C1
    class ERC20 <<(A,#228B22) abstract contract>> #FFB6C1
    class ERC20Facet <<(C,#1E90FF) contract>> #FFB6C1
    class ERC20Internal <<(A,#228B22) abstract contract>> #FFB6C1

    ERC20 --|> IERC20Isbe
    IERC20Isbe --|> IERC20
    IERC20Isbe --|> IERC20Metadata
    ERC20Internal --|> DidDocumentDetailedInternal 
    ERC20Facet --|> ERC20
    ERC20 --|> ERC203643InternalCommon

    
    ' --- Burnable---
    class IERC20Burnable <<(I,#FFD700) interface>> #FFB6C1
    class ERC20Burnable <<(A,#228B22) abstract contract>> #FFB6C1
    class ERC20BurnableFacet <<(C,#1E90FF) contract>> #FFB6C1

    ERC20Burnable --|> IERC20Burnable
    ERC20BurnableFacet --|> ERC20Burnable
    ERC20Burnable --|> ERC203643InternalCommon


    ' --- Snapshot---
    class IERC20Snapshot <<(I,#FFD700) interface>> #FFB6C1
    class ERC20Snapshot <<(A,#228B22) abstract contract>> #FFB6C1
    class ERC20SnapshotFacet <<(C,#1E90FF) contract>> #FFB6C1
    class ERC20SnapshotInternal <<(A,#228B22) abstract contract>> #FFB6C1

    ERC20Snapshot --|> IERC20Snapshot
    ERC20SnapshotFacet --|> ERC20Snapshot
    ERC20SnapshotInternal --|> ERC20Internal
    ERC20Snapshot --|> ERC203643InternalCommon
    ERC203643InternalCommon --|> ERC20SnapshotInternal



    ' --- Capped---
    class IERC203643Capped <<(I,#FFD700) interface>> #FFFF99
    class ERC203643Capped <<(A,#228B22) abstract contract>> #FFFF99
    class ERC203643CappedFacet <<(C,#1E90FF) contract>> #FFFF99
    class ERC203643CappedInternal <<(A,#228B22) abstract contract>> #FFFF99

    ERC203643Capped --|> IERC203643Capped
    ERC203643Capped --|> ERC203643CappedInternal
    ERC203643CappedFacet --|> ERC203643Capped
    ERC203643CappedInternal --|> ERC203643InternalCommon 
    ERC203643Capped --|> ERC203643InternalCommon


    ' --- Controller---
    class IERC203643Controller <<(I,#FFD700) interface>> #FFFF99
    class ERC203643ControllerInternal <<(A,#228B22) abstract contract>> #FFFF99
    class ERC203643Controller <<(A,#228B22) abstract contract>> #FFFF99
    class ERC203643ControllerFacet <<(C,#1E90FF) contract>> #FFFF99

    ERC203643Controller --|> IERC203643Controller
    ERC203643ControllerFacet --|> ERC203643Controller
    ERC203643Controller --|> ERC203643ControllerInternal

    ' --- Freeze ---
    class IERC3643Freeze <<(I,#FFD700) interface>> #77DD77
    class ERC3643FreezeInternal <<(A,#228B22) abstract contract>> #77DD77
    class ERC3643Freeze <<(A,#228B22) abstract contract>> #77DD77
    class ERC3643FreezeFacet <<(C,#1E90FF) contract>> #77DD77

    ERC3643FreezeFacet --|> ERC3643Freeze
    ERC3643Freeze --|> IERC3643Freeze  
    ERC3643Freeze --|> ERC203643InternalCommon
    ERC3643FreezeInternal --|> DidDocumentDetailedInternal 
    ERC203643InternalCommon --|> ERC3643FreezeInternal


    ' --- Metadata ---
    class IERC20Metadata <<(I,#FFD700) interface>> #FFB6C1
    class IERC3643Metadata <<(I,#FFD700) interface>> #77DD77
    class ERC3643Metadata <<(A,#228B22) abstract contract>> #77DD77
    class ERC3643MetadataFacet <<(C,#1E90FF) contract>> #77DD77

    ERC3643MetadataFacet --|> ERC3643Metadata 
    ERC3643Metadata --|> IERC3643Metadata 
    ERC3643Metadata --|> ERC203643InternalCommon
  

    ' --- Compliance Internals---
    class ERC3643ComplianceInternal <<(A,#228B22) abstract contract>> #E6E6FA
    class ERC3643ComplianceMaxBalanceInternal <<(A,#228B22) abstract contract>> #E6E6FA
    class ERC3643ComplianceDMLimInternal<<(A,#228B22) abstract contract>> #E6E6FA
    
    ERC203643InternalCommon --|> ERC3643ComplianceInternal   
    ERC3643ComplianceMaxBalanceInternal --|> ERC20Internal
    ERC3643ComplianceInternal --|> ERC3643ComplianceMaxBalanceInternal 
    ERC3643ComplianceDMLimInternal--|> DidDocumentDetailedInternal
    ERC3643ComplianceInternal --|> ERC3643ComplianceDMLimInternal


}
@enduml