// SPDX-License-Identifier: Apache-2.0

/* -----------------------------------------------------------------------------------
Copyright (c) 2025 Comunidad de Madrid & Alastria
Licensed under the Apache License, Version 2.0 (the "License");
You may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
----------------------------------------------------------------------------------- */
pragma solidity ^0.8.28;

/// @title ITimeStampingRegistry
/// @notice Interface for TimeStamping Registry contract providing hash registry services
/// @dev Defines the standard interface for timestamping registry operations including
///      hash stamping, signature-based operations, and data retrieval with originalHash as primary key
/// @author ISBE Team
/// @custom:security-level 3
/// @custom:auditor ISBE Security Team

/// @notice Struct containing signed TSR data for EIP712 signature verification
/// @dev Contains the TSR data along with signature metadata for secure off-chain signing
struct SignedTsrData {
    /// @notice The TSR data to be stamped
    TsrData tsrData;
    /// @notice The address of the signer
    address sender;
    /// @notice The expiration timestamp for the signature
    uint256 deadline;
    /// @notice The nonce to prevent replay attacks
    uint256 nonce;
}

/// @notice Struct to store TimeStamping Registry data
/// @dev Contains the core data for TSR operations including all three unique hashes
struct TsrData {
    /// @notice The original hash (input data hash, primary key)
    bytes32 originalHash;
    /// @notice The TSA hash (keccak256 of RFC 3161 Timestamp Response)
    bytes32 tsaHash;
    /// @notice The external reference ID (generated by backend for off-chain linkage)
    bytes32 externalReferenceId;
}

/// @notice Build TSR data struct from individual components
/// @param _originalHash The original hash (primary key)
/// @param _tsaHash The TSA hash
/// @param _externalReferenceId The external reference ID
/// @return tsrData_ The constructed TSR data struct
function _buildTsrData(
    bytes32 _originalHash,
    bytes32 _tsaHash,
    bytes32 _externalReferenceId
) pure returns (TsrData memory tsrData_) {
    return
        TsrData({
            originalHash: _originalHash,
            tsaHash: _tsaHash,
            externalReferenceId: _externalReferenceId
        });
}

/// @title ITimeStampingRegistry
/// @notice Interface for TimeStamping Registry contract providing hash registry services
/// @dev Defines the standard interface for timestamping registry operations including
///      hash stamping, signature-based operations, and data retrieval with originalHash as primary key
/// @author ISBE Team
/// @custom:security-level 3
/// @custom:auditor ISBE Security Team
interface ITimeStampingRegistry {
    /// @notice Event emitted when a TSR hash set is successfully stamped
    /// @param originalHash The original hash that was stamped (primary key)
    /// @param tsaHash The TSA hash that was stamped
    /// @param externalReferenceId The external reference ID associated with the hashes
    event Stamped(
        bytes32 indexed originalHash,
        bytes32 indexed tsaHash,
        bytes32 indexed externalReferenceId
    );

    /// @notice Error thrown when a hash is not found in the registry
    /// @param hash The hash that was not found
    error HashNotFound(bytes32 hash);

    /// @notice Error thrown when a hash already exists in the registry
    /// @param hash The hash that already exists
    error HashAlreadyExists(bytes32 hash);

    /// @notice Error thrown when an external reference ID already exists in the registry
    /// @param externalReferenceId The external reference ID that already exists
    error ExternalReferenceIdAlreadyExists(bytes32 externalReferenceId);

    /// @notice Stamp the provided hash set with direct method
    /// @dev Creates a new timestamp record for the given hashes (authority = requester = msg.sender)
    /// @param _originalHash The original hash to be stamped (primary key)
    /// @param _tsaHash The TimeStamping Authority response hash
    /// @param _externalReferenceId The external reference ID associated with the hashes
    function stamp(
        bytes32 _originalHash,
        bytes32 _tsaHash,
        bytes32 _externalReferenceId
    ) external;

    /// @notice Stamp the provided TSR data with a signature
    /// @dev Creates a new timestamp record using EIP712 signature verification
    ///      (authority = msg.sender, requester = SignedTsrData.sender)
    /// @param _tsrData The TimeStamping Registry data to be stamped
    /// @param _signature The signature associated with the TSR data
    function stampWithSignature(
        SignedTsrData calldata _tsrData,
        bytes calldata _signature
    ) external;

    /// @notice Check if an original hash is registered
    /// @dev Returns true if the original hash exists in the registry
    /// @param _originalHash The original hash to check
    /// @return exists_ A boolean indicating whether the original hash is registered
    function isOriginalHashRegistered(
        bytes32 _originalHash
    ) external view returns (bool exists_);

    /// @notice Check if a TSA hash is registered
    /// @dev Returns true if the TSA hash exists in the registry
    /// @param _tsaHash The TimeStamping Authority hash to check
    /// @return exists_ A boolean indicating whether the TSA hash is registered
    function isTsaHashRegistered(
        bytes32 _tsaHash
    ) external view returns (bool exists_);

    /// @notice Get the complete TSR record for a given original hash
    /// @dev Returns the TSR data along with authority and requester information
    /// @param _originalHash The original hash to query (primary key)
    /// @return tsrData The TSR data associated with the hash
    /// @return authority The address that stamped the hash
    /// @return requester The address that requested the stamping
    function getTsrRecordFromOriginalHash(
        bytes32 _originalHash
    )
        external
        view
        returns (TsrData memory tsrData, address authority, address requester);

    /// @notice Check if an external reference ID is registered
    /// @dev Returns true if the external reference ID exists in the registry
    /// @param _externalReferenceId The external reference ID to check
    /// @return exists_ A boolean indicating whether the external reference ID is registered
    function isExternalReferenceIdRegistered(
        bytes32 _externalReferenceId
    ) external view returns (bool exists_);

    /// @notice Get the total number of stamped entries
    /// @dev Returns the size of the stamped data registry
    /// @return size_ The total number of stamped entries
    function getStampedSize() external view returns (uint256 size_);

    /// @notice Get a paginated list of stamped TSR data
    /// @dev Returns TSR data for the specified page with pagination support
    /// @param _pageSize The number of items to retrieve per page
    /// @param _pageIndex The index of the page to retrieve (0-based)
    /// @return datas_ An array of TimeStamping Registry data on the specified page
    function getPaginatedStamped(
        uint256 _pageSize,
        uint256 _pageIndex
    ) external view returns (TsrData[] memory datas_);
}
