name: Code Quality Check

on:
    pull_request:
        branches:
            - main

jobs:
    code-quality:
        name: Code Quality Checks
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/actions/init

            - name: Run pre-commit
              run: npm run pre-commit

            - name: Install Slither & solc
              run: |
                  pip install slither-analyzer solc-select
                  solc-select install 0.8.28
                  solc-select use 0.8.28

            - name: Run Slither Analysis
              run: slither:analysis:local
